### ISSUE TITLE
No sé como funciona >_<

### ISSUE THREAD

**Issue by livrasand** [sws2apps/jw-epub-parser#365]
¿Como puedo probarlo?

**Comment by rhahao** [comment]
Hello @livrasand, thanks for reaching out!
Are you trying to use it in the browser, or for a nodejs app?

**Comment by rhahao** [comment]
Sure! I guess you’ve already installed it using the `npm install jw-epub-parser` command.
The next step would be to import it into your project:

- For client application, you would simply use:
```js
import { loadEPUB } from 'jw-epub-parser'
```
- For Node app, use:
```js
import { loadEPUB } from 'jw-epub-parser/dist/node/index.js'
```

The `loadEPUB` is an asynchronous function can accept one of these three arguments: the path to the EPUB file (node only) or EPUB file's blob (browser only) or url to download the EPUB file (you need to get the correct url from jw.org).

Example:
```js
const result = await loadEPUB({ url: 'https://download-a.akamaihd.net/files/media_periodical/84/mwb_E_202307.epub' })
```

You will get the meeting workbook data, as explained in [this section](https://github.com/sws2apps/jw-epub-parser#return) if everything goes well.

**Comment by rhahao** [comment]
You’re welcome! I will close this issue then, but feel free to reopen it or create a new one if you have questions.

**Comment by ux-git** [comment]
Hola @livrasand! ¿Cómo estás? Would you be interested in participating in development a new version of the [Organized app](https://github.com/sws2apps/organized-app)? It's the app that uses this epub parser tool to make it possible to screate meeting schedules in only a few seconds.

We are working on the redesign and then plan to add new useful features, therefore looking for enthusiastic brothers who would like to help us with the frontend development.
We will be very glad if you have interest to contribute ☺️ Of course, only as your time allows you to.

So, if you're interested, let me know how I can reach you out. Thanks in advance!
