### ISSUE TITLE
Help for using jw-epub-parser

### ISSUE THREAD

**Issue by user-kh** [sws2apps/jw-epub-parser#570]
Hi @rhahao,
thanks for your great work.
Your jw-epub-parser is a great project.

I would like to use it. I have the following problem:
1) At the beginning I wanted to use your app in the browser via URL. However, the website does not allow it because of **CORS**.

2) Secondly, I wanted to read the file locally in the browser via **<input type="file">** and pass it on as **readAsDataURL(blob)**. But that didn't work. The following error message appears:
"You are using the Browser version of jw-epub-parser. Please switch to the Node version if needed."

What am I doing wrong? 
How can I use it correctly?

Thank you for your answer
_best regards_

**Comment by rhahao** [comment]
Hello @user-kh, thanks for reaching out!

1. If you still have an idea of accessing an URL to get the data, I’ve switched recently to a new URL to solve the CORS issue. Now it can be accessed here: `https://api-source-materials.sws2apps.com/api/:language`. The cons is not all languages are supported there.
2. I have an example using it in the browser here in this [file](https://github.com/sws2apps/jw-epub-parser/blob/main/client/src/App.jsx). Could you check if it may help?

Thank you!

**Comment by user-kh** [comment]
Hi @rhahao thank you very much for your quick answer.  I tried your second suggestion.  Now it worked!  Many thanks for your support

**Comment by user-kh** [comment]
Hey @ux-git, 

Thank you for your message.  

I find the Organised App project very exciting. Basically, I would like to support you. However, I have no experience in developing with Firebase. In order to be able to help you, I need appropriate training.  

If you like, you can also contact me personally. You can use the following
[https://fern.my-router.de/umfrage/index.php/542412?lang=de](link)

**Comment by user-kh** [comment]
Hey @ux-git 
I sent you a private message via email
