### ISSUE TITLE
request new language support

### ISSUE THREAD

**Issue by xellosiris** [sws2apps/jw-epub-parser#875]
### Add a brief description for this request

I would like to request new language: Chinese Mandarin (Traditional)

**Comment by rhahao** [comment]
Hi @xellosiris, thank you for your request. We’ll check this and get back to you asap.

**Comment by rhahao** [comment]
Hi @xellosiris, the [Chinese Mndarin (Traditional)](https://crowdin.com/project/cpe-jw-epub-parser/cmnl) is now available for translation in Crowdin. Can you please help with the translating the required texts? Thanks.

**Comment by xellosiris** [comment]
Thank you for your invitation. Considering my current situation, I may not have extra time to take on the translation work. I'm sorry.btw, I already finished the translation.
